version: '3'

services: 
    app:
        build: .
        env_file: .env
        container_name: recipe-app
        ports: 
            - "5000:8000"
        volumes: 
            - .:/app/src
        depends_on: 
            - db
        command: ['bash', '-c', 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py runserver 0.0.0.0:8000']
    
    db:
        env_file: .env
        image: postgres
        volumes: 
            - /var/lib/postgresql